# Generated by Django 5.0.6 on 2024-06-27 18:03

import applications.core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='published', max_length=50, verbose_name='Status')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Event time')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('photo', models.ImageField(blank=True, help_text='Max size 800x800px. JPG', null=True, upload_to=applications.core.models.PathAndRename('map/marker/photo'), verbose_name='Photo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'marker',
                'verbose_name_plural': 'markers',
                'ordering': ['-created'],
            },
        ),
    ]
