# Generated by Django 5.0.6 on 2024-07-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_marker_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='Time'),
        ),
    ]
