# Generated by Django 5.0.6 on 2024-07-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_marker_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time'),
        ),
    ]
