# Generated by Django 5.0.6 on 2024-07-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_marker_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of modification'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=50, verbose_name='Status'),
        ),
    ]
