# Generated by Django 5.0.6 on 2024-07-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude_center',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude center of the map'),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude_center',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude center of the map'),
        ),
    ]
