# Generated by Django 5.0.6 on 2024-07-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_latitude_center_user_longitude_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='map_zoom',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Zoom of the map'),
        ),
    ]
