# Generated by Django 5.0.6 on 2024-07-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_map_zoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_language',
            field=models.CharField(blank=True, max_length=16, verbose_name='Telegram language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram username'),
        ),
    ]
